version: '3.9'
services:
  bot:
    build:
      context: .
    volumes:
      - ./docker_config.py:/code/config.py
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: tg_app
      POSTGRES_PASSWORD: tg_app_password
      POSTGRES_DB: tg_app
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U flask_app" ]
      interval: 5s
      timeout: 5s
      retries: 5